### ISSUE TITLE
Emoji on mac os Sierra does not work

### ISSUE THREAD

**Issue by andrewMuntyan** [kkartaltepe/obs-text-pango#7]

**Comment by andrewMuntyan** [comment]
maybe i have not understood how to use it :)
<img width="1117" alt="2018-04-20_0208" src="https://user-images.githubusercontent.com/1164826/39022754-c30640ce-443f-11e8-9021-29855af9fccb.png">

**Comment by kkartaltepe** [comment]
v0.3 has been fixed. A new package is up on releases.

**Comment by kkartaltepe** [comment]
Did some testing on emoji while i was on mac. There are a number of issues. Unfortunately the libraries available for mac are slightly out of date due to bugs. Otherwise its a similar issue with windows. The emoji fonts supported by Pango are not supported by the Operating System.

I might end up shipping a configuration similar to how I do on windows if nothing changes in the state of emoji support before I'm ready for this plugin to come out of beta (1-2 months from now).

**Comment by kkartaltepe** [comment]
Newest update has a new version of the supporting library. This enables emojis on Mac.
